### ISSUE TITLE
Missing tests/mixins.py file in 1.4.9 PyPI archive

### ISSUE THREAD

**Issue by arkamar** [IlyaSkriblovsky/txredisapi#149]
I am currently working on creating a Gentoo package for `txredisapi` and I've noticed that the `tests/mixins.py` file is missing from the PyPI archive for version 1.4.9. In Gentoo, we prefer using the PyPI archive for the package source, but due to the missing `tests/mixins.py` file, the tests are failing. Everything works fine from Github sources.

Here is a snippet from the test log:
```
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twisted/trial/runner.py", line 616, in loadPackage
    module = modinfo.load()
  File "/usr/lib/python3.10/site-packages/twisted/python/modules.py", line 388, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python3.10/site-packages/twisted/python/reflect.py", line 297, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python3.10/site-packages/twisted/python/reflect.py", line 244, in _importAndCheckStack
    raise excValue.with_traceback(excTraceback)
  File "/var/tmp/portage/dev-python/txredisapi-1.4.9/work/txredisapi-1.4.9/tests/test_basics.py", line 20, in <module>
    from .mixins import REDIS_HOST, REDIS_PORT
builtins.ModuleNotFoundError: No module named 'tests.mixins'

tests.test_basics
```

Btw, `tests/chash_distribution.py` is also missing in the archive, but this does not cause any problems.

**Comment by arkamar** [comment]
cc @fiorix (based on PyPI related PRs and Issues)

**Comment by arkamar** [comment]
PyPI archive for version 1.4.10 is missing tests completely.
